#!/usr/bin/env node
// Compiles the operator-assigned graphic key -> earring-graphic map.
// Studio binds a Stripe Product ID to one of these stable graphic keys. Listing
// text and price come from Stripe; inventory comes from the shop Worker.
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const rootDir = path.dirname(fileURLToPath(import.meta.url));
const palette = JSON.parse(await readFile(path.join(rootDir, 'palette.json'), 'utf8'));
const graphics = JSON.parse(await readFile(path.join(rootDir, 'graphics.json'), 'utf8'));

for (const [graphicKey, graphic] of Object.entries(graphics)) {
  if (!graphicKey.trim()) throw new Error('graphics.json: every graphic key must be non-empty');
  if (!graphic.slug || !Number.isInteger(graphic.node)) {
    throw new Error(`${graphicKey}: graphic needs a slug and integer node`);
  }
  if (!palette[graphic.colors?.accent]) {
    throw new Error(`${graphicKey}: colors.accent must name a palette family`);
  }
  const { frames } = graphic;
  if (!frames?.sheet || ![frames.fw, frames.fh, frames.cols, frames.count]
    .every((value) => Number.isInteger(value) && value > 0)) {
    throw new Error(`${graphicKey}: frames need sheet, fw, fh, cols, and count`);
  }
}

const visuals = Object.fromEntries(Object.entries(graphics).map(([graphicKey, graphic]) => [graphicKey, {
  ...graphic,
  frames: { ...graphic.frames, sheet: `source/earrings/${graphic.frames.sheet}` },
}]));

const content = `// Generated by source/earrings/build-entries.mjs. Do not edit.\n` +
  `window.EARRING_COLOR_PALETTE = ${JSON.stringify(palette)};\n` +
  `window.EARRING_VISUALS = ${JSON.stringify(visuals)};\n`;
await writeFile(path.join(rootDir, 'entries.js'), content);
console.log(`built ${Object.keys(visuals).length} earring visual${Object.keys(visuals).length === 1 ? '' : 's'} -> source/earrings/entries.js`);
