window.EARRINGS_PAGE_SOURCE = [
  {
    slug: "blue-resin",
    title: "Blue Resin Diamond",
    price: 52,
    quantity: 2,
    materials: "resin, sterling silver",
    made: "summer 2026",
    description: `Hand-poured resin diamond on a thread. It swings and settles — grab it and
it wiggles.`,
    preset: "single-media",
    node: 31,
    colors: {"title":"1a1a1a","subtitle":"3b5a8a","description":"444444","background":"f7f4ee","brightness":"light"},
    mediaFiles: {"images":[],"videos":[]},
    mediaTop: null,
    mediaBottom: null,
    frames: {"sheet":"source/earrings/blue-resin/frames.png","fw":250,"fh":235,"cols":8,"rows":4,"count":32,"frameMs":43}
  },
  {
    slug: "blue-screw",
    title: "Blue Screw",
    price: 52,
    quantity: 2,
    materials: "steel, sterling silver",
    made: "fall 2026",
    description: `A single screw, hung from its head. It swings and settles — grab it and it wiggles.`,
    preset: "single-media",
    node: 36,
    colors: {"title":"1a1a1a","subtitle":"3b5a8a","description":"444444","background":"f7f4ee","brightness":"light"},
    mediaFiles: {"images":[],"videos":[]},
    mediaTop: null,
    mediaBottom: null,
    frames: {"sheet":"source/earrings/blue-screw/frames.png","fw":250,"fh":191,"cols":8,"rows":4,"count":32,"frameMs":90}
  },
  {
    slug: "blue-wood",
    title: "Blue Wood Drop",
    price: 52,
    quantity: 2,
    materials: "dyed wood, sterling silver",
    made: "fall 2026",
    description: `Dyed wood on a thread. It swings and settles — grab it and it wiggles.`,
    preset: "single-media",
    node: 37,
    colors: {"title":"1a1a1a","subtitle":"3b5a8a","description":"444444","background":"f7f4ee","brightness":"light"},
    mediaFiles: {"images":[],"videos":[]},
    mediaTop: null,
    mediaBottom: null,
    frames: {"sheet":"source/earrings/blue-wood/frames.png","fw":154,"fh":226,"cols":8,"rows":4,"count":32,"frameMs":55}
  },
  {
    slug: "clear-resin-drop",
    title: "Clear Resin Drop",
    price: 52,
    quantity: 2,
    materials: "resin, sterling silver",
    made: "fall 2026",
    description: `A clear resin drop on a thread. It swings and settles — grab it and it wiggles.`,
    preset: "single-media",
    node: 38,
    colors: {"title":"1a1a1a","subtitle":"6b6b6b","description":"444444","background":"f7f4ee","brightness":"light"},
    mediaFiles: {"images":[],"videos":[]},
    mediaTop: null,
    mediaBottom: null,
    frames: {"sheet":"source/earrings/clear-resin-drop/frames.png","fw":132,"fh":226,"cols":8,"rows":4,"count":32,"frameMs":186}
  },
  {
    slug: "clear-resin-triangle",
    title: "Clear Resin Triangle",
    price: 52,
    quantity: 2,
    materials: "resin, sterling silver",
    made: "fall 2026",
    description: `Clear cast resin triangle on a thread. It swings and settles — grab it and it wiggles.`,
    preset: "single-media",
    node: 39,
    colors: {"title":"1a1a1a","subtitle":"6b6b6b","description":"444444","background":"f7f4ee","brightness":"light"},
    mediaFiles: {"images":[],"videos":[]},
    mediaTop: null,
    mediaBottom: null,
    frames: {"sheet":"source/earrings/clear-resin-triangle/frames.png","fw":164,"fh":210,"cols":8,"rows":4,"count":32,"frameMs":193}
  },
  {
    slug: "duo-screw",
    title: "Duo Screw",
    price: 52,
    quantity: 2,
    materials: "steel, sterling silver",
    made: "fall 2026",
    description: `Two screws on one thread, swinging out of step. Grab it and it wiggles.`,
    preset: "single-media",
    node: 40,
    colors: {"title":"1a1a1a","subtitle":"555555","description":"444444","background":"f7f4ee","brightness":"light"},
    mediaFiles: {"images":[],"videos":[]},
    mediaTop: null,
    mediaBottom: null,
    frames: {"sheet":"source/earrings/duo-screw/frames.png","fw":130,"fh":176,"cols":8,"rows":4,"count":32,"frameMs":106}
  },
  {
    slug: "green-resin",
    title: "Green Resin Diamond",
    price: 52,
    quantity: 2,
    materials: "resin, sterling silver",
    made: "summer 2026",
    description: `Hand-poured resin diamond on a thread. It swings and settles — grab it and
it wiggles.`,
    preset: "single-media",
    node: 34,
    colors: {"title":"1a1a1a","subtitle":"3b6b4a","description":"444444","background":"f7f4ee","brightness":"light"},
    mediaFiles: {"images":[],"videos":[]},
    mediaTop: null,
    mediaBottom: null,
    frames: {"sheet":"source/earrings/green-resin/frames.png","fw":129,"fh":234,"cols":8,"rows":4,"count":32,"frameMs":73}
  },
  {
    slug: "gummy-worm",
    title: "Gummy Worm",
    price: 52,
    quantity: 2,
    materials: "resin, sterling silver",
    made: "fall 2026",
    description: `A resin gummy worm on a thread. It swings and settles — grab it and it wiggles.`,
    preset: "single-media",
    node: 41,
    colors: {"title":"1a1a1a","subtitle":"8a6d3b","description":"444444","background":"f7f4ee","brightness":"light"},
    mediaFiles: {"images":[],"videos":[]},
    mediaTop: null,
    mediaBottom: null,
    frames: {"sheet":"source/earrings/gummy-worm/frames.png","fw":250,"fh":250,"cols":8,"rows":4,"count":32,"frameMs":102}
  },
  {
    slug: "loop-study",
    title: "Pipeline Loop Study",
    price: 52,
    quantity: 0,
    materials: "sterling silver, test staging",
    made: "fall 2026",
    description: `Test staging of the earring asset automation pipeline output: loop-trim -> spaced-frames(12) -> stabilize-on-point. Staged here to judge the stabilized swing in the real shop context. Not for sale.`,
    preset: "single-media",
    node: 35,
    colors: {"title":"1a1a1a","subtitle":"8a6d3b","description":"444444","background":"f7f4ee","brightness":"light"},
    mediaFiles: {"images":[],"videos":[]},
    mediaTop: null,
    mediaBottom: null,
    frames: {"sheet":"source/earrings/loop-study/frames.png","fw":500,"fh":500,"cols":4,"rows":3,"count":12,"frameMs":286}
  },
  {
    slug: "pin-hanger",
    title: "Pin Hanger",
    price: 52,
    quantity: 2,
    materials: "sterling silver",
    made: "fall 2026",
    description: `A pinned hanger on a thread. It swings and settles — grab it and it wiggles.`,
    preset: "single-media",
    node: 42,
    colors: {"title":"1a1a1a","subtitle":"8a3b4a","description":"444444","background":"f7f4ee","brightness":"light"},
    mediaFiles: {"images":[],"videos":[]},
    mediaTop: null,
    mediaBottom: null,
    frames: {"sheet":"source/earrings/pin-hanger/frames.png","fw":109,"fh":243,"cols":8,"rows":4,"count":32,"frameMs":47}
  },
  {
    slug: "red-diamond",
    title: "Red Rose Diamond",
    price: 52,
    quantity: 2,
    materials: "resin, dried rose, sterling silver",
    made: "summer 2026",
    description: `Hand-poured resin diamond with a dried rose suspended inside. Hung on a
thread, it swings and settles — grab it and it wiggles.`,
    preset: "single-media",
    node: 32,
    colors: {"title":"1a1a1a","subtitle":"8a3b3b","description":"444444","background":"f7f4ee","brightness":"light"},
    mediaFiles: {"images":[],"videos":[]},
    mediaTop: null,
    mediaBottom: null,
    frames: {"sheet":"source/earrings/red-diamond/frames.png","fw":145,"fh":192,"cols":8,"rows":4,"count":32,"frameMs":90}
  },
  {
    slug: "red-wood",
    title: "Red Wood Drop",
    price: 52,
    quantity: 2,
    materials: "dyed wood, sterling silver",
    made: "fall 2026",
    description: `Dyed red wood on a thread. It swings and settles — grab it and it wiggles.`,
    preset: "single-media",
    node: 43,
    colors: {"title":"1a1a1a","subtitle":"8a3b3b","description":"444444","background":"f7f4ee","brightness":"light"},
    mediaFiles: {"images":[],"videos":[]},
    mediaTop: null,
    mediaBottom: null,
    frames: {"sheet":"source/earrings/red-wood/frames.png","fw":143,"fh":208,"cols":8,"rows":4,"count":32,"frameMs":62}
  },
  {
    slug: "yellow-blue-hanger",
    title: "Yellow Blue Hanger",
    price: 52,
    quantity: 2,
    materials: "enamel, sterling silver",
    made: "fall 2026",
    description: `Yellow and blue hanger on a thread. It swings and settles — grab it and it wiggles.`,
    preset: "single-media",
    node: 44,
    colors: {"title":"1a1a1a","subtitle":"8a6b3b","description":"444444","background":"f7f4ee","brightness":"light"},
    mediaFiles: {"images":[],"videos":[]},
    mediaTop: null,
    mediaBottom: null,
    frames: {"sheet":"source/earrings/yellow-blue-hanger/frames.png","fw":106,"fh":225,"cols":8,"rows":4,"count":32,"frameMs":27}
  },
  {
    slug: "yellow-resin",
    title: "Yellow Resin Diamond",
    price: 52,
    quantity: 2,
    materials: "resin, sterling silver",
    made: "summer 2026",
    description: `Hand-poured resin diamond on a thread. It swings and settles — grab it and
it wiggles.`,
    preset: "single-media",
    node: 33,
    colors: {"title":"1a1a1a","subtitle":"8a6b3b","description":"444444","background":"f7f4ee","brightness":"light"},
    mediaFiles: {"images":[],"videos":[]},
    mediaTop: null,
    mediaBottom: null,
    frames: {"sheet":"source/earrings/yellow-resin/frames.png","fw":159,"fh":208,"cols":8,"rows":4,"count":32,"frameMs":78}
  },
  {
    slug: "yellow-wood",
    title: "Yellow Wood Drop",
    price: 52,
    quantity: 2,
    materials: "dyed wood, sterling silver",
    made: "fall 2026",
    description: `Dyed yellow wood on a thread. It swings and settles — grab it and it wiggles.`,
    preset: "single-media",
    node: 45,
    colors: {"title":"1a1a1a","subtitle":"8a6b3b","description":"444444","background":"f7f4ee","brightness":"light"},
    mediaFiles: {"images":[],"videos":[]},
    mediaTop: null,
    mediaBottom: null,
    frames: {"sheet":"source/earrings/yellow-wood/frames.png","fw":159,"fh":204,"cols":8,"rows":4,"count":32,"frameMs":46}
  },
  {
    slug: "yellow-wood-2",
    title: "Yellow Wood Drop II",
    price: 52,
    quantity: 2,
    materials: "dyed wood, sterling silver",
    made: "fall 2026",
    description: `Dyed yellow wood on a thread — second cut. It swings and settles — grab it and it wiggles.`,
    preset: "single-media",
    node: 46,
    colors: {"title":"1a1a1a","subtitle":"8a6b3b","description":"444444","background":"f7f4ee","brightness":"light"},
    mediaFiles: {"images":[],"videos":[]},
    mediaTop: null,
    mediaBottom: null,
    frames: {"sheet":"source/earrings/yellow-wood-2/frames.png","fw":135,"fh":250,"cols":8,"rows":4,"count":32,"frameMs":33}
  }
];
