window.EARRING_COLOR_PALETTE = {"yellow":{"light":"#e6ff81","mid":"#e3d90a","dark":"#bcab1c"},"orange":{"light":"#f7d782","mid":"#ffab2b","dark":"#d56012"},"red":{"light":"#ffbd7d","mid":"#fe5f41","dark":"#cb3f2e"},"violet":{"light":"#ffaecf","mid":"#ff8dba","dark":"#cb2e8a"},"purple":{"light":"#edb8f7","mid":"#d26de8","dark":"#a036dd"},"bluie":{"light":"#9ddbfb","mid":"#72aff3","dark":"#5563d6"},"green":{"light":"#7eeeb4","mid":"#0dc9af","dark":"#218c7e"}};

window.EARRINGS_PAGE_SOURCE = [
  {
    slug: "blue-orange-gummyworms",
    title: "Blue Orange Gummy Worms",
    price: 52,
    quantity: 2,
    materials: "lampwork glass, mixed-media beads, gold-plated findings",
    made: "fall 2026",
    description: `One-of-a-kind earring in the current collection. Drag it across the grid to see the motion.`,
    preset: "single-media",
    node: 31,
    colors: {"title":"1a1a1a","subtitle":"3b5a8a","description":"444444","background":"f7f4ee","brightness":"light","accent":"bluie"},
    mediaFiles: {"images":[],"videos":[]},
    mediaTop: null,
    mediaBottom: null,
    frames: {"sheet":"source/earrings/blue-orange-gummyworms/frames.png","fw":188,"fh":394,"cols":8,"rows":4,"count":30,"frameMs":33}
  },
  {
    slug: "blue-yellow-gummy-bear",
    title: "Blue Yellow Gummy Bear",
    price: 52,
    quantity: 2,
    materials: "lampwork glass, mixed-media beads, gold-plated findings",
    made: "fall 2026",
    description: `One-of-a-kind earring in the current collection. Drag it across the grid to see the motion.`,
    preset: "single-media",
    node: 32,
    colors: {"title":"1a1a1a","subtitle":"3b5a8a","description":"444444","background":"f7f4ee","brightness":"light","accent":"bluie"},
    mediaFiles: {"images":[],"videos":[]},
    mediaTop: null,
    mediaBottom: null,
    frames: {"sheet":"source/earrings/blue-yellow-gummy-bear/frames.png","fw":178,"fh":365,"cols":8,"rows":4,"count":32,"frameMs":33}
  },
  {
    slug: "nb-chandelier",
    title: "NB Chandelier",
    price: 52,
    quantity: 2,
    materials: "vintage glass beads, freshwater pearl, gold-filled wire",
    made: "fall 2026",
    description: `One-of-a-kind earring in the current collection. Drag it across the grid to see the motion.`,
    preset: "single-media",
    node: 33,
    colors: {"title":"1a1a1a","subtitle":"555555","description":"444444","background":"f7f4ee","brightness":"light","accent":"purple"},
    mediaFiles: {"images":[],"videos":[]},
    mediaTop: null,
    mediaBottom: null,
    frames: {"sheet":"source/earrings/nb-chandelier/frames.png","fw":201,"fh":309,"cols":8,"rows":4,"count":32,"frameMs":33}
  },
  {
    slug: "pink-lolipop",
    title: "Pink Lollipop",
    price: 52,
    quantity: 2,
    materials: "lampwork glass, resin bead, gold-plated findings",
    made: "fall 2026",
    description: `One-of-a-kind earring in the current collection. Drag it across the grid to see the motion.`,
    preset: "single-media",
    node: 34,
    colors: {"title":"1a1a1a","subtitle":"8a3b6b","description":"444444","background":"f7f4ee","brightness":"light","accent":"violet"},
    mediaFiles: {"images":[],"videos":[]},
    mediaTop: null,
    mediaBottom: null,
    frames: {"sheet":"source/earrings/pink-lolipop/frames.png","fw":188,"fh":389,"cols":8,"rows":4,"count":32,"frameMs":33}
  },
  {
    slug: "purple-lolipop",
    title: "Purple Lollipop",
    price: 52,
    quantity: 2,
    materials: "lampwork glass, resin bead, gold-plated findings",
    made: "fall 2026",
    description: `One-of-a-kind earring in the current collection. Drag it across the grid to see the motion.`,
    preset: "single-media",
    node: 35,
    colors: {"title":"1a1a1a","subtitle":"6b3b8a","description":"444444","background":"f7f4ee","brightness":"light","accent":"purple"},
    mediaFiles: {"images":[],"videos":[]},
    mediaTop: null,
    mediaBottom: null,
    frames: {"sheet":"source/earrings/purple-lolipop/frames.png","fw":206,"fh":412,"cols":8,"rows":4,"count":32,"frameMs":33}
  },
  {
    slug: "red-yellow-gummyworms",
    title: "Red Yellow Gummy Worms",
    price: 52,
    quantity: 2,
    materials: "lampwork glass, mixed-media beads, gold-plated findings",
    made: "fall 2026",
    description: `One-of-a-kind earring in the current collection. Drag it across the grid to see the motion.`,
    preset: "single-media",
    node: 36,
    colors: {"title":"1a1a1a","subtitle":"8a4c3b","description":"444444","background":"f7f4ee","brightness":"light","accent":"red"},
    mediaFiles: {"images":[],"videos":[]},
    mediaTop: null,
    mediaBottom: null,
    frames: {"sheet":"source/earrings/red-yellow-gummyworms/frames.png","fw":204,"fh":434,"cols":8,"rows":4,"count":32,"frameMs":33}
  },
  {
    slug: "yellow-gummy-bear",
    title: "Yellow Gummy Bear",
    price: 52,
    quantity: 2,
    materials: "lampwork glass, mixed-media beads, gold-plated findings",
    made: "fall 2026",
    description: `One-of-a-kind earring in the current collection. Drag it across the grid to see the motion.`,
    preset: "single-media",
    node: 37,
    colors: {"title":"1a1a1a","subtitle":"8a6b3b","description":"444444","background":"f7f4ee","brightness":"light","accent":"yellow"},
    mediaFiles: {"images":[],"videos":[]},
    mediaTop: null,
    mediaBottom: null,
    frames: {"sheet":"source/earrings/yellow-gummy-bear/frames.png","fw":224,"fh":359,"cols":8,"rows":4,"count":32,"frameMs":33}
  }
];
